config/routes.rb
Rails.application.routes.draw do
  get 'users/profile/:id', to: 'users#show', as: 'profile'
  devise_for :users, :path_prefix => 'my'
  resources :users
  resources :stories
  root 'stories#index'
  get 'users/dashboard/:id', to: 'users#dashboard', as: 'panel_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :sign_up_config, if: :devise_controller?
    before_action :user_update_config, if: :devise_controller?

    protected

    def sign_up_config
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def user_update_config
        devise_parameter_sanitizer.permit(:account_update, keys: [:admin, :name])
    end

    def authorize_admin!
        redirect_to root_path unless current_user.admin
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]

  # GET /stories or /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1 or /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = current_user

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: "Story was successfully created." }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :picture, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize_admin!, only: [:dashboard]

    def show
        @user = User.find(params[:id])        
        @stories = @user.stories
    end

    def dashboard
        @users = User.all
        @stories = Story.all
    end

    def edit
        @user = User.find(params[:id])   
    end 

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to panel_admin_path
        else
            render 'edit'
        end
    end

    private

    def user_params
      params.require(:user).permit(:admin, :name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <polyline points="5 12 3 12 12 3 21 12 19 12" />
  <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
  <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
</svg>'.html_safe, root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <% if user_signed_in? %>
        <li class="nav-item active">
            <%= link_to '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />
  <path d="M7 12h14l-3 -3m0 6l3 -3" />
</svg> Log Out'.html_safe, destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>
        <li class="nav-item active">
            <%= link_to '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <circle cx="12" cy="7" r="4" />
  <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
</svg> Profile'.html_safe, profile_path(current_user.id), class:'nav-link' %>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <line x1="12" y1="5" x2="12" y2="19" />
  <line x1="5" y1="12" x2="19" y2="12" />
</svg> Sign Up'.html_safe, new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-login" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />
  <path d="M20 12h-13l3 -3m0 6l-3 -3" />
</svg> Log in'.html_safe, new_user_session_path, class:'nav-link' %>
        </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |f| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group w-50">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="form-group w-50">
    <%= f.label :picture %>
    <%= f.text_field :picture, class:'form-control' %>
  </div>

  <div class="form-group w-50">
    <%= f.label :content %>
    <%= f.text_field :content, class:'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Create story", class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1 class="pb-4">Stories</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Picture</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= image_tag story.picture, class:'img-fluid' %></td>
        <td><%= story.content %></td>
        <td><%= story.user.name %></td>
      <% if user_signed_in? && current_user == story.user %>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% elsif user_signed_in? && current_user.admin %>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>
        <td><%= link_to 'Show', story %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path, class:'badge badge-secondary' %>

app/views/stories/new.html.erb
<h1 class='pb-3'>New Story</h1>

<%= render 'form', story: @story %>

<br>
<br>

<%= link_to 'Back', stories_path, class: 'badge badge-secondary' %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @story.picture, class:'img-fluid' %>
</p>

<p>
  <strong>Content:</strong>
  <%= @story.content %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/users/dashboard.html.erb
<h1 class="pb-5">Dashboard Admin</h1>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Admin</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><% if user.admin %>
                        <%= pp "Yes" %>
                    <% else %>
                        <%= pp "No" %>
                    <% end %>
                </td>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

  <div class="form-group">
    <%= f.label :admin, 'Admin' %><br />
    <%= f.select :admin, options_for_select([['On', true], ['Off', false]]), class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email", class:'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class: 'btn btn-primary' %>
  </div>
<% end %>

<br>

<%= link_to 'Back', panel_admin_path(current_user) %>

app/views/users/show.html.erb
<h1 class=>User Account</h1>

<ul class="py-3">
  <li>Name: <%= current_user.name %></li> 
  <li>Email:  <%= current_user.email %></li>
</ul>
<div class="pb-5"> 
  <%= link_to 'Edit Profile', edit_user_registration_url, class:'badge badge-primary' %>

  <% if user_signed_in? && current_user.admin %>
      <%= link_to 'Admin Panel', panel_admin_path(current_user), class:'badge badge-primary' %>
  <% end %>
</div>


<h2 class="py-3 text-center">Stories</h2>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Picture</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= image_tag story.picture, class:'img-fluid' %></td>
        <td><%= story.content %></td>
      <% if user_signed_in? && current_user == story.user %>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% elsif user_signed_in? && current_user.admin %>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>
        <td><%= link_to 'Show', story %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>